### ISSUE TITLE
pytorchモデルが正しくロードされない

### ISSUE THREAD

**Issue by masakifujiwara1** [open-rdc/nav_cloning#16]
モデルをロードした際に, 出力の値がほぼ動きません.

**Comment by masakifujiwara1** [comment]
*net.pyのload部分を下記のように変更
https://github.com/masakifujiwara1/nav_cloning/blob/747c54f5bfe25944a835ff67da5989c37ba4a959/scripts/nav_cloning_with_direction_net.py#L226

**Comment by haruyama8940** [comment]
修正に感謝します
マージし，issueを閉じます
