### ISSUE TITLE
Willow_Garageのシミュレーションにおける移動する物体の配置方法について

### ISSUE THREAD

**Issue by 21C1072takahashishoku** [open-rdc/nav_cloning#19]
今回issueを投稿させていただいたのは、タイトルの示す通りで、シミュレーション上で物体（円柱）を移動させる方法ことが現時点でできていないため、投稿させていただきました。
具体的には、物体をシミュレーションで一定ステップごとに、指定した範囲内で移動するようにさせたいと考えております。

**Comment by yasuohayashibara** [comment]
ここまでできたけどこれができないというようにピンポイントで問題を聞くようにしましょう．
また，ブランチを切って開発途中のソースコードがあるとより詳しいアドバイスができると思います．

**Comment by yasuohayashibara** [comment]
とりあえずChatGPTに聞いてみました．
これで解決するかは分かりませんが，手がかりは得られると思います．

gazeboで円柱を置いて，時間の経過に合わせてランダムに移動させる方法を教えて

ChatGPT
Gazeboシミュレータで円柱を配置し、時間の経過に伴ってランダムに移動させる方法についてご説明します。これを実現するためには、以下のステップに従ってください。

Gazebo環境のセットアップ:

Gazeboシミュレーション環境をインストールしていない場合は、まずインストールしてください。
Gazeboを起動し、基本的な環境をセットアップします。
円柱のモデルを作成またはインポート:

Gazeboのモデルデータベースから円柱モデルを選択するか、独自の3Dモデルをインポートします。
円柱の配置:

Gazeboのワールドエディタを使用して円柱を配置します。
プラグインまたはスクリプトの作成:

時間の経過に伴い円柱をランダムに移動させるために、カスタムプラグインまたはスクリプトを作成する必要があります。このスクリプトは、特定の時間間隔で円柱の位置を更新します。
スクリプトの実装:

以下は、Pythonを使用してGazebo内の円柱をランダムに移動させる基本的な例です。ROS（Robot Operating System）と組み合わせて使用することもできます。
python

```
import random
import time
import rospy
from gazebo_msgs.srv import SetModelState
from gazebo_msgs.msg import ModelState

# ROSノードの初期化
rospy.init_node('move_cylinder')

# サービスが利用可能になるまで待機
rospy.wait_for_service('/gazebo/set_model_state')
set_state = rospy.ServiceProxy('/gazebo/set_model_state', SetModelState)

while not rospy.is_shutdown():
    # 新しい位置をランダムに生成
    new_x = random.uniform(-5, 5)
    new_y = random.uniform(-5, 5)

    # ModelStateオブジェクトの設定
    model_state = ModelState()
    model_state.model_name = 'cylinder_model' # モデル名を指定
    model_state.pose.position.x = new_x
    model_state.pose.position.y = new_y

    # 状態更新のリクエスト
    try:
        set_state(model_state)
    except rospy.ServiceException as e:
        print("Service call failed: %s" % e)

    # 次の移動までの待機時間
    time.sleep(5)
```

このスクリプトでは、/gazebo/set_model_stateサービスを使用して、特定の間隔で円柱の位置をランダムに更新しています。

スクリプトの実行:

このスクリプトを実行すると、指定された時間間隔ごとに円柱がランダムな位置に移動します。
トラブルシューティングと調整:

**Comment by 21C1072takahashishoku** [comment]
ご回答ありがとうございます。
現状としましては、障害物をワールドに配置することはできましたが、それを一定範囲内でランダムに移動させるということができておりません。
送っていただいたプログラムを一度試してみたいと思います。

**Comment by 21C1072takahashishoku** [comment]
自分自身でも同じようにchatGPTに聞き、プログラムなどを行いましたが、起動しませんでした。
いろいろと調べた結果、自分の環境のrosserviceがうまく行っていない体と思います。
具体的には、rosservice listと入力しても、/rosout/get_loggersと/rosout/set_logger_levelしか出ないという結果でした。
なので、現在の問題としては、rosserviceが少ないという現状の解決をしなければならないと考えております。
`#!/usr/bin/env python3

import rospy
import random
from gazebo_msgs.msg import ModelStates
from gazebo_msgs.srv import ApplyBodyWrench
from geometry_msgs.msg import Wrench

def move_cylinder():
    rospy.init_node('move_cylinder_node', anonymous=True)

    # 適切なモデル名に変更
    model_name = "your_cylinder_model_name"

    # ランダムな位置に円柱を配置
    # ここでは例として、x, y, zの範囲を指定しています
    x = random.uniform(-5, 5)
    y = random.uniform(-5, 5)
    z = random.uniform(0, 2)
    #ここまで反応したこれ以降反応なし
    rospy.wait_for_service('/gazebo/apply_body_wrench')
    apply_wrench = rospy.ServiceProxy('/gazebo/apply_body_wrench', ApplyBodyWrench)

    # ランダムな力を生成
    force = Wrench()
    force.force.x = random.uniform(-10, 10)
    force.force.y = random.uniform(-10, 10)
    force.force.z = random.uniform(0, 5)

    # ランダムな力を円柱に加える
    apply_wrench(model_name, "world", (x, y, z), force, rospy.Time(), rospy.Duration(1.0))

if __name__ == '__main__':
    move_cylinder()`

**Comment by 21C1072takahashishoku** [comment]
自分自身でも同じようにchatGPTに聞き、プログラムなどを行いましたが、起動しませんでした。
いろいろと調べた結果、自分の環境のrosserviceがうまく行っていない体と思います。
具体的には、rosservice listと入力しても、/rosout/get_loggersと/rosout/set_logger_levelしか出ないという結果でした。
なので、現在の問題としては、rosserviceが少ないという現状の解決をしなければならないと考えております。
以下のコードを現在使用しております。
このコードのrospy.wait_for_service('/gazebo/apply_body_wrench'というところで引っかかってしまっていると思われます。

```#!/usr/bin/env python3

import rospy
import random
from gazebo_msgs.msg import ModelStates
from gazebo_msgs.srv import ApplyBodyWrench
from geometry_msgs.msg import Wrench

def move_cylinder():
    rospy.init_node('move_cylinder_node', anonymous=True)

    # 適切なモデル名に変更
    model_name = "your_cylinder_model_name"

    # ランダムな位置に円柱を配置
    # ここでは例として、x, y, zの範囲を指定しています
    x = random.uniform(-5, 5)
    y = random.uniform(-5, 5)
    z = random.uniform(0, 2)
    #ここまで反応したこれ以降反応なし
    rospy.wait_for_service('/gazebo/apply_body_wrench')
    apply_wrench = rospy.ServiceProxy('/gazebo/apply_body_wrench', ApplyBodyWrench)

    # ランダムな力を生成
    force = Wrench()
    force.force.x = random.uniform(-10, 10)
    force.force.y = random.uniform(-10, 10)
    force.force.z = random.uniform(0, 5)

    # ランダムな力を円柱に加える
    apply_wrench(model_name, "world", (x, y, z), force, rospy.Time(), rospy.Duration(1.0))

if __name__ == '__main__':
    move_cylinder()```

**Comment by yasuohayashibara** [comment]
ChatGPTはあくまでもヒントをくれるツールと思ったほうが良いです．
正解は自分で導き出すことが必要です．

`/gazebo/set_model_state`ですが，コマンドラインからでも使用できるようです．
プログラムを作成する前に試してみたほうが良いかもしれません．

https://classic.gazebosim.org/tutorials?tut=ros_comm&cat=connect_ros

**Comment by 21C1072takahashishoku** [comment]
ありがとうございます。プログラムを作成する前に試してみようと思います。

**Comment by 21C1072takahashishoku** [comment]
/gazebo/set_model_stateを行った結果、そのようなファイルやディレクトリはありませんと出ました。
現状の目標としては、とりあえず円柱を自分の作成したワールドに追加することを目標としています。

**Comment by 21C1072takahashishoku** [comment]
シミュレーション環境で一定の時間が経過したあとある範囲の中で障害物を移動させることができましたので、動画を取りました。以下のURLからご覧ください。具体的には、更新時間は３秒、移動範囲は部屋の一室だけとなっております。
https://www.youtube.com/watch?v=lEQ3ynPJXyE
今後としましては、現在は障害物の移動間隔が秒数で指定しているので、これを秒数ではなくstep数で移動刷るようにさせたいと考えています。

**Comment by yasuohayashibara** [comment]
できれば，使用したスクリプトをこちらに貼って，issueを閉じてもらえればと思います．

**Comment by 21C1072takahashishoku** [comment]
了解しました。こちらが今回使用したプログラムです。
spawn_model.py

```
#!/usr/bin/env python3

import rospy
from gazebo_msgs.srv import SpawnModel
from geometry_msgs.msg import Pose

def spawn_gazebo_model(model_name, model_file, x, y, z):
    rospy.wait_for_service('/gazebo/spawn_sdf_model')
    try:
        spawn_model = rospy.ServiceProxy('/gazebo/spawn_sdf_model', SpawnModel)
        with open(model_file, 'r') as f:
            model_xml = f.read()
        pose = Pose()
        pose.position.x = x
        pose.position.y = y
        pose.position.z = z
        spawn_model(model_name, model_xml, '', pose, 'world')
        rospy.loginfo("Spawned model: {}".format(model_name))
    except rospy.ServiceException as e:
        rospy.logerr("Service call failed: {}".format(e))

if __name__ == '__main__':
    rospy.init_node('spawn_model_node')
    model_name = 'my_cylinder_model'
    model_file = '/home/ciero/catkin_ws/src/my_models/my_cylinder/cylinder.sdf'  # モデルファイルのパスを指定
    x, y, z = 19.0, 7.3, 0.0  # スポーンする位置
    spawn_gazebo_model(model_name, model_file, x, y, z)
```


move_model.py

```
#!/usr/bin/env python3

import rospy
from gazebo_msgs.srv import SetModelState
from gazebo_msgs.msg import ModelState
import random
import time

def set_model_state(model_name, x, y, z):
    rospy.wait_for_service('/gazebo/set_model_state')
    try:
        set_model_state = rospy.ServiceProxy('/gazebo/set_model_state', SetModelState)
        model_state = ModelState()
        model_state.model_name = model_name
        model_state.pose.position.x = x
        model_state.pose.position.y = y
        model_state.pose.position.z = z
        set_model_state(model_state)
        rospy.loginfo(f"Moved model {model_name} to x={x}, y={y}, z={z}")
    except rospy.ServiceException as e:
        rospy.logerr("Service call failed: {}".format(e))

if __name__ == '__main__':
    rospy.init_node('move_model_node')
    model_name = 'my_cylinder_model'

    while not rospy.is_shutdown():
        # 一定区間内でランダムな座標を生成
        x = random.uniform(15.0, 21.0)
        y = random.uniform(5.0, 11.0)
        z = random.uniform(0.0, 0.0)
    

        set_model_state(model_name, x, y, z)

        # 3秒待機
        time.sleep(3)
```

**Comment by 21C1072takahashishoku** [comment]
また、これをステップ数毎に変化させることをしたいと思っていますが、それはまた別のissueに投稿するという形でよろしいいでしょうか

**Comment by yasuohayashibara** [comment]
そうですね．
issueはできるだけ焦点を絞って短期間で解決できるものにしたほうが良いです．

**Comment by 21C1072takahashishoku** [comment]
返信遅れてしまい申し訳ありません。
了解しました。では、こちらを閉じさせてもらいたいと思います。
問題解決に向けたアドバイスなど誠にありがとうございました。
